frigateNetwork:
  webPort: 31000
  enableRtmp: true
  rtmpPort: 31001
  enableRtsp: true
  rtspPort: 31002
  enableWebRtc: true
  webRtcPort: 31003
  enableAuthenticatedUI: true
  authenticatedUIPort: 31004

frigateStorage:
  config:
    type: pvc
  media:
    type: pvc
  cache:
    sizeGiB: 2
  shm:
    sizeMiB: 128
