frigateNetwork:
  enableRtmp: true
  enableRtsp: true
  enableWebRtc: true
  enableAuthenticatedUI: true
  hostNetwork: true

frigateStorage:
  config:
    type: pvc
  media:
    type: pvc
  cache:
    sizeGiB: 2
  shm:
    sizeMiB: 128
